server:
  port: 8080

spring:
  application:
    name: backend
  profiles:
    active: local

  datasource:
    url: jdbc:mysql://localhost:3306/playlist_db?serverTimezone=Asia/Seoul&characterEncoding=utf8
    username: myapp_user
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        # Dialect 에러 방지를 위해 명시
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

youtube:
  base-url: https://www.googleapis.com/youtube/v3